# to run the container, use the command:
# docker-compose up --build
# docker compose run --rm --service-ports nari-tts
services:
  nari-tts:
    image: nari-tts:latest
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    stdin_open: true
    tty: true
    command: /bin/bash
    volumes:
      - .:/mnt